<a href="https://colab.research.google.com/github/vaibhavgupta2499/ColabWorks/blob/main/marvel_char.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [63]:
df=pd.read_csv('/content/drive/MyDrive/marvelCharactersDataset/charcters_stats.csv')

In [39]:
df

Name Alignment  Intelligence  ...  Power  Combat  Total
0            3-D Man      good            50  ...     25      52    233
1             A-Bomb      good            38  ...     17      64    316
2         Abe Sapien      good            88  ...     35      85    299
3           Abin Sur      good            50  ...     84      65    406
4        Abomination       bad            63  ...     55      95    436
..               ...       ...           ...  ...    ...     ...    ...
606     Yellowjacket      good            88  ...     12      14    164
607  Yellowjacket II      good            50  ...     31      28    182
608             Ymir      good            50  ...     83      28    388
609          Zatanna      good            75  ...    100      56    292
610             Zoom       bad            50  ...     72      28    288

[611 rows x 9 columns]

In [40]:
for x in list(df.columns):
  print(x+' - '+str(df[x].isnull().sum()))

Name - 0
Alignment - 3
Intelligence - 0
Strength - 0
Speed - 0
Durability - 0
Power - 0
Combat - 0
Total - 0


In [41]:
df.Alignment.unique()

array(['good', 'bad', nan, 'neutral'], dtype=object)

In [64]:
df['Alignment'].fillna('neutral',inplace=True)

In [43]:
df['Alignment'].isnull().sum()

0

In [44]:
df.Alignment.unique()

array(['good', 'bad', 'neutral'], dtype=object)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 611 entries, 0 to 610
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Name          611 non-null    object
 1   Alignment     611 non-null    object
 2   Intelligence  611 non-null    int64 
 3   Strength      611 non-null    int64 
 4   Speed         611 non-null    int64 
 5   Durability    611 non-null    int64 
 6   Power         611 non-null    int64 
 7   Combat        611 non-null    int64 
 8   Total         611 non-null    int64 
dtypes: int64(7), object(2)
memory usage: 43.1+ KB


In [46]:
df.describe()

Intelligence    Strength       Speed  ...       Power      Combat       Total
count    611.000000  611.000000  611.000000  ...  611.000000  611.000000  611.000000
mean      44.502455   29.083470   27.306056  ...   40.312602   43.206219  226.250409
std       32.924722   32.610939   25.760173  ...   34.539910   33.270329  167.324034
min        1.000000    1.000000    1.000000  ...    0.000000    1.000000    5.000000
25%        1.000000    1.000000    1.000000  ...    0.000000    1.000000    5.000000
50%       50.000000   10.000000   23.000000  ...   37.000000   50.000000  255.000000
75%       75.000000   53.000000   42.000000  ...   67.000000   70.000000  351.500000
max      113.000000  100.000000  100.000000  ...  100.000000  101.000000  581.000000

[8 rows x 7 columns]

In [65]:
df.drop('Total',axis='columns',inplace=True)

In [48]:
df.head()

Name Alignment  Intelligence  ...  Durability  Power  Combat
0      3-D Man      good            50  ...          32     25      52
1       A-Bomb      good            38  ...          80     17      64
2   Abe Sapien      good            88  ...          42     35      85
3     Abin Sur      good            50  ...          64     84      65
4  Abomination       bad            63  ...          90     55      95

[5 rows x 8 columns]

In [49]:
col=list(df.columns)
col.remove('Name')
col.remove('Alignment')
print(col)

['Intelligence', 'Strength', 'Speed', 'Durability', 'Power', 'Combat']


In [50]:
min_max_arr=[[0 for i in range(6)] for j in range(3)]
print(min_max_arr)

[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]


In [51]:
i=0
for c in col:
  min_max_arr[0][i]=df[c].min()
  min_max_arr[1][i]=df[c].max()
  min_max_arr[2][i]=c
  i=i+1
print(min_max_arr)

[[1, 1, 1, 1, 0, 1], [113, 100, 100, 120, 100, 101], ['Intelligence', 'Strength', 'Speed', 'Durability', 'Power', 'Combat']]


In [66]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df[col] = scaler.fit_transform(df[col])

In [53]:
df.head()

Name Alignment  Intelligence  ...  Durability  Power  Combat
0      3-D Man      good      0.437500  ...    0.260504   0.25    0.51
1       A-Bomb      good      0.330357  ...    0.663866   0.17    0.63
2   Abe Sapien      good      0.776786  ...    0.344538   0.35    0.84
3     Abin Sur      good      0.437500  ...    0.529412   0.84    0.64
4  Abomination       bad      0.553571  ...    0.747899   0.55    0.94

[5 rows x 8 columns]

In [54]:
df.describe()

Intelligence    Strength       Speed  Durability       Power      Combat
count    611.000000  611.000000  611.000000  611.000000  611.000000  611.000000
mean       0.388415    0.283671    0.265718    0.343190    0.403126    0.422062
std        0.293971    0.329403    0.260204    0.307091    0.345399    0.332703
min        0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%        0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
50%        0.437500    0.090909    0.222222    0.260504    0.370000    0.490000
75%        0.660714    0.525253    0.414141    0.663866    0.670000    0.690000
max        1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

In [70]:
dff=pd.get_dummies(df[['Alignment']])
ddff=pd.concat([df,dff],axis=1)
ddff.drop('Alignment',axis='columns',inplace=True)

In [71]:
ddff.head()

Name  Intelligence  ...  Alignment_good  Alignment_neutral
0      3-D Man      0.437500  ...               1                  0
1       A-Bomb      0.330357  ...               1                  0
2   Abe Sapien      0.776786  ...               1                  0
3     Abin Sur      0.437500  ...               1                  0
4  Abomination      0.553571  ...               0                  0

[5 rows x 10 columns]

In [72]:
from sklearn import linear_model, metrics

X = ddff.drop("Name", axis=1)
y = ddff["Name"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)


from sklearn.linear_model import LogisticRegression

logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)

predictions = logmodel.predict(X_test)

In [74]:
np.size(predictions)

184

In [84]:
predictions

array(['Zoom', 'Nova', 'Nova', 'Blue Beetle I', 'Luke Campbell', 'Nova',
       'Red Skull', 'Punisher', 'Kevin 11', 'Nova', 'Giganta', 'Darkseid',
       'Punisher', 'Blue Beetle I', 'Blue Beetle I', 'Darkseid',
       'Solomon Grundy', 'Blue Beetle I', 'Red Hood', 'Giganta',
       'Blue Beetle I', 'Nova', 'Darkseid', 'Red Skull', 'Blue Beetle I',
       'Rhino', 'Blue Beetle I', 'Luke Campbell', 'Luke Campbell', 'Nova',
       'Blue Beetle I', 'Nova', 'Mister Mxyzptlk', 'Luke Campbell',
       'Trickster', 'Nova', 'Luke Campbell', 'Nova', 'Darkseid',
       'General Zod', 'Punisher', 'Nova', 'Abraxas', 'Blue Beetle I',
       'Blue Beetle I', 'Nova', 'Nova', 'Blue Beetle I', 'Blue Beetle I',
       'Anti-Venom', 'General Zod', 'Blue Beetle I', 'Nova',
       'Blue Beetle I', 'Blue Beetle I', 'Blue Beetle I', 'Bizarro',
       'General Zod', 'Blue Beetle I', 'Red Skull', 'Luke Campbell',
       'Professor X', 'General Zod', 'Professor X', 'Luke Campbell',
       'Nova', 'Nova', 'Kevi

In [86]:
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier().fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)
print(dtree_predictions)

['Exodus' 'Silverclaw' 'Isis' 'Adam Strange' 'Ammo' 'Green Arrow'
 'Goblin Queen' 'Sage' 'Siren' 'Cyborg' 'Green Goblin' 'Blackout' 'Ronin'
 'Adam Strange' 'Adam Strange' 'Klaw' 'Mister Freeze' 'Adam Strange'
 'Trickster' 'Deathstroke' 'Adam Strange' 'Power Girl' 'Onslaught'
 'Kraven the Hunter' 'Adam Strange' 'Rhino' 'Adam Strange' 'Ammo' 'Ammo'
 'Superman' 'Adam Strange' 'Flash IV' 'Goblin Queen' 'Ammo' 'Toad'
 'Flash I' 'Ammo' 'Big Barda' 'Venom' 'Venom' 'Ronin' 'Lightning Lad'
 'Venom' 'Adam Strange' 'Adam Strange' 'Alfred Pennyworth' 'Ant-Man II'
 'Adam Strange' 'Adam Strange' 'Klaw' 'Magus' 'Adam Strange' 'Northstar'
 'Adam Strange' 'Adam Strange' 'Adam Strange' 'Apocalypse'
 'Cyborg Superman' 'Adam Strange' 'Arclight' 'Ammo' 'Nina Theroux'
 'Vulture' 'Violet' 'Ammo' 'Space Ghost' 'Namora' 'Scarlet Witch'
 'Adam Strange' 'Ymir' 'Deadman' 'Rhino' 'Kraven the Hunter' 'Molten Man'
 'Ammo' 'Ammo' 'Goblin Queen' 'Adam Strange' 'Adam Strange' 'Watcher'
 'Moon Knight' 'Blizzard II' 'Jus

In [89]:
print(y_test)

504             Siryn
407          Namorita
481    Scarlet Spider
100       Blaquesmith
425         Overtkill
            ...      
388              Mogo
535    Superboy-Prime
315             Joker
568          Valkyrie
205               Ego
Name: Name, Length: 184, dtype: object


In [87]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test,dtree_predictions )

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1859: UserWarning: y_pred contains classes not in y_true
  warnings.warn('y_pred contains classes not in y_true')


0.0

In [79]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predictions)
print(cm)
print(np.size(cm))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
45369


In [78]:
from sklearn.metrics import precision_recall_fscore_support
a=precision_recall_fscore_support(y_test, predictions)
print(a)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [80]:
from sklearn.metrics import average_precision_score
average_precision_score(y_test, predictions)

ValueError: ignored

In [83]:
from sklearn.metrics import precision_score
precision_score(y_test, predictions,average=None)

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
def func(st):
  if(st=='good'):
    return(1)
  elif(st=='neutral'):
    return(0)
  else:
    return(-1)
df['Alignment']=df.apply(lambda row : func(row['Alignment']), axis = 1)

In [21]:
df.head()

Name  Alignment  Intelligence  ...  Durability  Power  Combat
0      3-D Man          1      0.437500  ...    0.260504   0.25    0.51
1       A-Bomb          1      0.330357  ...    0.663866   0.17    0.63
2   Abe Sapien          1      0.776786  ...    0.344538   0.35    0.84
3     Abin Sur          1      0.437500  ...    0.529412   0.84    0.64
4  Abomination         -1      0.553571  ...    0.747899   0.55    0.94

[5 rows x 8 columns]

In [22]:
df.describe()

Alignment  Intelligence    Strength  ...  Durability       Power      Combat
count  611.000000    611.000000  611.000000  ...  611.000000  611.000000  611.000000
mean     0.436989      0.388415    0.283671  ...    0.343190    0.403126    0.422062
std      0.887365      0.293971    0.329403  ...    0.307091    0.345399    0.332703
min     -1.000000      0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%     -1.000000      0.000000    0.000000  ...    0.000000    0.000000    0.000000
50%      1.000000      0.437500    0.090909  ...    0.260504    0.370000    0.490000
75%      1.000000      0.660714    0.525253  ...    0.663866    0.670000    0.690000
max      1.000000      1.000000    1.000000  ...    1.000000    1.000000    1.000000

[8 rows x 7 columns]